import { Amiri, Cormorant_Garamond } from "next/font/google";

// Display fonts via next/font (self-hosted at build time, not preloaded).
// The body fonts — IBM Plex Sans Arabic and Manrope — are self-hosted in /public/fonts
// (app/body-fonts.css, generated by scripts/fetch-fonts.ts) so that each locale can preload
// its own body font; next/font can only preload per layout, and /ar and /en share one.

/** Cormorant Garamond: only the weights the stylesheet uses (400 text, 500 headings/brand names). */
export const cormorant = Cormorant_Garamond({
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
  preload: false,
  variable: "--font-cormorant",
});

/** Amiri: a single weight (400). */
export const amiri = Amiri({
  weight: ["400"],
  subsets: ["arabic", "latin"],
  display: "swap",
  preload: false,
  variable: "--font-amiri",
});

export const fontVars = [cormorant.variable, amiri.variable].join(" ");

/** The body font file preloaded for each locale (see app/body-fonts.css). */
export const BODY_FONT_PRELOAD = {
  ar: "/fonts/ibm-plex-sans-arabic-400-arabic.woff2",
  en: "/fonts/manrope-latin.woff2",
} as const;
