// AUTO-GENERATED by scripts/extract-assets.ts — do not edit by hand.
// Intrinsic pixel sizes of the extracted assets (used for next/image width/height).

export const PHOTO_SIZES: Record<string, { w: number; h: number }> = {
  "inf_vanity": {
    "w": 848,
    "h": 1200
  },
  "inf_kitchen": {
    "w": 1200,
    "h": 848
  },
  "inf_island": {
    "w": 1200,
    "h": 848
  },
  "inf_agate": {
    "w": 1100,
    "h": 777
  },
  "inf_green": {
    "w": 1200,
    "h": 848
  },
  "roca_basin": {
    "w": 1100,
    "h": 825
  },
  "toto_lav": {
    "w": 1250,
    "h": 744
  },
  "toto_vessels": {
    "w": 1250,
    "h": 764
  },
  "toto_washlet": {
    "w": 1250,
    "h": 744
  },
  "vid_brick": {
    "w": 1000,
    "h": 968
  },
  "vid_diamond": {
    "w": 960,
    "h": 1200
  },
  "vid_hex": {
    "w": 1043,
    "h": 1200
  },
  "vid_pool": {
    "w": 739,
    "h": 960
  },
  "vid_titanium": {
    "w": 1200,
    "h": 1200
  },
  "vid_pool_out": {
    "w": 1920,
    "h": 1134
  },
  "inf_onyx": {
    "w": 1920,
    "h": 1080
  },
  "inf_floor": {
    "w": 1000,
    "h": 1113
  },
  "arg_wood": {
    "w": 1920,
    "h": 940
  },
  "arg_concrete": {
    "w": 1920,
    "h": 940
  },
  "arg_marble": {
    "w": 1920,
    "h": 940
  },
  "arg_rustic": {
    "w": 1920,
    "h": 940
  },
  "arg_texture": {
    "w": 1920,
    "h": 940
  },
  "arg_stone": {
    "w": 1920,
    "h": 940
  },
  "may_hydraulic": {
    "w": 1496,
    "h": 1092
  },
  "may_rustic": {
    "w": 1496,
    "h": 1092
  },
  "may_small": {
    "w": 1535,
    "h": 1228
  },
  "may_subway": {
    "w": 1920,
    "h": 1402
  },
  "roca_ohtake": {
    "w": 1920,
    "h": 1281
  },
  "roca_multiclean": {
    "w": 1600,
    "h": 1200
  },
  "roca_avant": {
    "w": 1600,
    "h": 1200
  },
  "roca_plenum": {
    "w": 1400,
    "h": 990
  },
  "roca_tenet_room": {
    "w": 1920,
    "h": 1440
  },
  "roca_inwall": {
    "w": 1920,
    "h": 1358
  },
  "roca_tenet": {
    "w": 1400,
    "h": 1050
  },
  "roca_nu": {
    "w": 1600,
    "h": 1200
  },
  "toto_acc": {
    "w": 1600,
    "h": 500
  },
  "toto_taps": {
    "w": 1250,
    "h": 738
  },
  "toto_bath": {
    "w": 1250,
    "h": 764
  },
  "toto_smart": {
    "w": 1250,
    "h": 764
  },
  "toto_nature": {
    "w": 1700,
    "h": 1152
  },
  "toto_garden": {
    "w": 1250,
    "h": 764
  },
  "ab_marble": {
    "w": 1920,
    "h": 1248
  },
  "ab_wood": {
    "w": 1867,
    "h": 1400
  },
  "ab_white": {
    "w": 1400,
    "h": 1050
  },
  "ab_xlab": {
    "w": 1400,
    "h": 1050
  },
  "inf_agate_bath": {
    "w": 1920,
    "h": 1080
  },
  "inf_rosso": {
    "w": 1920,
    "h": 1358
  },
  "inf_pietra": {
    "w": 1920,
    "h": 1080
  },
  "inf_patinato": {
    "w": 1920,
    "h": 1080
  },
  "inf_satin": {
    "w": 1920,
    "h": 1080
  }
};

export const LOGO_FILES: Record<string, { src: string; w: number; h: number }> = {
  "Nueva Alaplana": {
    "src": "/logos/alaplana.svg",
    "w": 466,
    "h": 135
  },
  "TOTO": {
    "src": "/logos/toto.svg",
    "w": 58,
    "h": 13
  },
  "Azulejos Benadresa": {
    "src": "/logos/benadresa.png",
    "w": 55,
    "h": 30
  },
  "Vidrepur": {
    "src": "/logos/vidrepur.svg",
    "w": 354,
    "h": 47
  },
  "Roca": {
    "src": "/logos/roca.svg",
    "w": 141,
    "h": 72
  },
  "Argenta Cerámica": {
    "src": "/logos/argenta.png",
    "w": 207,
    "h": 34
  },
  "Infinity Surfaces": {
    "src": "/logos/infinity-surfaces.svg",
    "w": 723,
    "h": 96
  },
  "Mayolica": {
    "src": "/logos/mayolica.png",
    "w": 338,
    "h": 94
  },
  "Laminam": {
    "src": "/logos/laminam.png",
    "w": 182,
    "h": 27
  }
};

export const BRAND_MARKS = {
  "wordmark": {
    "src": "/brand/midpoint-wordmark.webp",
    "w": 316,
    "h": 132
  },
  "heart": {
    "src": "/brand/midpoint-heart.webp",
    "w": 267,
    "h": 240
  }
} as const;
