/**
 * Self-hosts the two body fonts so each locale can preload its own file (next/font can only
 * preload per layout, and /ar and /en share one layout).
 *
 *   npm run fetch-fonts
 *
 * Writes:
 *   public/fonts/*.woff2      IBM Plex Sans Arabic 400 + 600 (arabic, latin), Manrope 400–600 (latin)
 *   app/body-fonts.css        @font-face rules, metric-matched fallbacks and the CSS variables
 *
 * Weight 500 is mapped onto the 600 file (IBM Plex Sans Arabic ships only 400 and 600 here),
 * so every `font-weight:500` in the stylesheet renders with the 600 cut — no CSS changes needed.
 * Display fonts (Cormorant Garamond, Amiri) stay on next/font in app/fonts.ts.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(__dirname, "..");
// Same user agent next/font uses, so the files are identical to what next/font would self-host.
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36";

type Face = { subset: string; weight: string; url: string; range: string };

async function faces(query: string): Promise<Face[]> {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?${query}&display=swap`, { headers: { "user-agent": UA } })).text();
  return [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)].map(([, subset, body]) => ({
    subset,
    weight: body.match(/font-weight:\s*([^;]+);/)![1].trim(),
    url: body.match(/url\(([^)]+)\)/)![1],
    range: body.match(/unicode-range:\s*([^;]+);/)![1].trim(),
  }));
}

async function main() {
  const out: string[] = [];
  const dir = path.join(ROOT, "public/fonts");
  await mkdir(dir, { recursive: true });

  const save = async (f: Face, name: string) => {
    const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer());
    await writeFile(path.join(dir, name), buf);
    console.log(`  ${name}  ${(buf.length / 1024).toFixed(0)} KiB`);
    return `/fonts/${name}`;
  };

  // IBM Plex Sans Arabic — 400 and 600; 600 also serves 500.
  for (const f of await faces("family=IBM+Plex+Sans+Arabic:wght@400;600")) {
    if (!["arabic", "latin"].includes(f.subset)) continue;
    const src = await save(f, `ibm-plex-sans-arabic-${f.weight}-${f.subset}.woff2`);
    const weight = f.weight === "600" ? "500 600" : f.weight;
    out.push(`/* IBM Plex Sans Arabic ${f.weight} (${f.subset})${f.weight === "600" ? " — also used for 500" : ""} */
@font-face{font-family:"IBM Plex Sans Arabic";font-style:normal;font-weight:${weight};font-display:swap;src:url(${src}) format("woff2");unicode-range:${f.range}}`);
  }

  // Manrope — variable font, the 400–600 range actually used.
  for (const f of await faces("family=Manrope:wght@400..600")) {
    if (f.subset !== "latin") continue;
    const src = await save(f, `manrope-${f.subset}.woff2`);
    out.push(`/* Manrope 400–600 (${f.subset}, variable) */
@font-face{font-family:"Manrope";font-style:normal;font-weight:400 600;font-display:swap;src:url(${src}) format("woff2");unicode-range:${f.range}}`);
  }

  const css = `/*
 * AUTO-GENERATED by scripts/fetch-fonts.ts — self-hosted body fonts.
 * Stable URLs so app/[locale]/layout.tsx can preload the current locale's body font.
 */
${out.join("\n")}

/* Metric-matched fallbacks (same values next/font generates) to avoid layout shift on swap */
@font-face{font-family:"IBM Plex Sans Arabic Fallback";src:local("Arial");ascent-override:107.25%;descent-override:41.02%;line-gap-override:0%;size-adjust:101.17%}
@font-face{font-family:"Manrope Fallback";src:local("Arial");ascent-override:103.31%;descent-override:29.07%;line-gap-override:0%;size-adjust:103.19%}

:root{--font-plex-arabic:"IBM Plex Sans Arabic","IBM Plex Sans Arabic Fallback";--font-manrope:"Manrope","Manrope Fallback"}
`;
  await writeFile(path.join(ROOT, "app/body-fonts.css"), css);
  console.log("  app/body-fonts.css");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
